# Stack Name = CloudFormation-Stack-Example-First-Template
# AMI ID - Linux Amazon 2 - sa-east-1 = ami-09344f463b780bd4c
Parameters:
  ImageId:
    Description: 'Write down the EC2 AMI ID of the region you are creating this stack'
    Type: 'String'

  BucketName:
    Description: 'Write down the bucket Name'
    Type: 'String'

  OwnerTag:
    Description: 'Write down the owner tag to the resources'
    Type: 'String'

  KeyPairName:
    Description: 'Select the KeyPair to connetc to the Ec2 instance through SSH'
    Type: AWS::EC2::KeyPair::KeyName
    
Resources:  
  Bucket: 
    Type: 'AWS::S3::Bucket'
    Properties:   
      BucketName: !Ref BucketName
      Tags:
        - Key: 'Owner'
          Value: !Ref OwnerTag
  
  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: !Ref KeyPairName
      InstanceType: 't2.micro'
      ImageId: !Ref ImageId
      Tags:
        - Key: 'Owner'
          Value: !Ref OwnerTag
        - Key: 'Name'
          Value: 'EC2 Instance CloudFormation Lab'
      
