Parameters:
  BucketName:
    Type: 'String'
    Description: 'Write down the Bucket Name'

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      Tags:
        - Key: 'Owner'
          Value: 'GuilhermeCosme'
